# Generated by Django 5.0.4 on 2024-05-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trener', '0002_alter_injuries_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.TextField()),
            ],
            options={
                'verbose_name': 'Тип матча',
                'verbose_name_plural': 'Типы матчей',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.TextField()),
                ('EndTime', models.TextField()),
                ('Score', models.FloatField()),
                ('TeamA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='trener.team')),
                ('TeamB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='trener.team')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='referee.matchtype')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='Deletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reazon', models.TextField()),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletes', to='trener.player')),
                ('MatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletes', to='referee.match')),
            ],
            options={
                'verbose_name': 'Удаление',
                'verbose_name_plural': 'Удаления',
            },
        ),
        migrations.CreateModel(
            name='Aletrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reazon', models.TextField()),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trener.player')),
                ('MatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='referee.match')),
            ],
            options={
                'verbose_name': 'Предупреждение',
                'verbose_name_plural': 'Предупреждения',
            },
        ),
    ]
