# Generated by Django 5.0.4 on 2024-05-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0001_initial'),
        ('trener', '0003_playerdetails_penalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reazon', models.TextField()),
                ('ChangedPlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_player', to='trener.player')),
                ('MatchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_on_match', to='referee.match')),
                ('NewPlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_player', to='trener.player')),
            ],
            options={
                'verbose_name': 'Замены',
                'verbose_name_plural': 'Замены',
            },
        ),
    ]
