# Generated by Django 5.0.4 on 2024-05-14 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0002_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changes',
            name='Reazon',
        ),
    ]
