# Generated by Django 5.0.4 on 2024-05-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0003_remove_changes_reazon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='Score',
        ),
        migrations.AddField(
            model_name='match',
            name='ScoreA',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='ScoreB',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
