# Generated by Django 5.0.4 on 2024-05-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0007_alter_match_endtime_alter_match_scorea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='EndTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ScoreA',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ScoreB',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
