# Generated by Django 5.0.4 on 2024-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0008_alter_match_endtime_alter_match_scorea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GolTypeName', models.CharField(max_length=12)),
                ('Points', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Тип Гола',
                'verbose_name_plural': 'Типы голов',
            },
        ),
    ]
