# Generated by Django 5.0.4 on 2024-06-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0009_golstypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gols',
            name='GolType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols_types', to='referee.golstypes'),
        ),
    ]
