# Generated by Django 5.0.4 on 2024-06-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0012_alter_gols_goltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gols',
            name='GolType1',
        ),
        migrations.AlterField(
            model_name='gols',
            name='GolType',
            field=models.CharField(choices=[('attempt', 'Попытка'), ('realization', 'Реализация'), ('penalty', 'Штрафной'), ('dropgol', 'Дроп-гол')], max_length=12),
        ),
    ]
