# Generated by Django 5.0.4 on 2024-06-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0013_remove_gols_goltype1_alter_gols_goltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gols',
            name='GolTypeA',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='gols_type', to='referee.golstypes'),
            preserve_default=False,
        ),
    ]
