# Generated by Django 5.0.4 on 2024-05-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='injuries',
            options={'verbose_name': 'Травма', 'verbose_name_plural': 'Травмы'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='playerdetails',
            options={'verbose_name': 'Детали Игрока', 'verbose_name_plural': 'Детали Игроков'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
