# Generated by Django 5.0.4 on 2024-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0002_alter_injuries_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdetails',
            name='penalty',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
